[build]
  publish = "dist"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://todo-backend-d4rk.onrender.com"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://todo-backend-d4rk.onrender.com"

[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://todo-backend-d4rk.onrender.com"
