services:
  - type: web
    name: todo-backend
    env: python
    plan: free
    rootDir: Backend
    buildCommand: pip install -r todo_backend/requirements.txt
    startCommand: python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn todo_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 3
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://todo-backend.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: todo-postgres
          property: connectionString

databases:
  - name: todo-postgres
    plan: free
