services:
  - type: web
    name: todo-backend
    env: python
    plan: free
    rootDir: Backend
    buildCommand: pip install -r todo_backend/requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn todo_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 3
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://todo-backend.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: todo-postgres
          property: connectionString
    autoDeploy: true

  - type: static_site
    name: todo-frontend
    plan: free
    rootDir: Frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: todo-backend
          type: web
          property: url

databases:
  - name: todo-postgres
    plan: free
